site:
  title: zhangzr的网站
  description: zhang zr
  keywords: gitsite, git, static web site, html
  theme: default
  language: en-ZH
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  # root-path: /gitsite
  # set cdn path:
  cdn-path: https://cdn.jsdelivr.net/npm
  navigation:
    # - title: User Guide
      # uri: /books/gitsite-guide/index.html
    - title: AI编程
      uri: /books/ai-program/index.html
    - title: 博客
      uri: /blogs/tech/index.html
    # - title: License
    #   uri: /pages/license/index.html
    # - title: Discuss
    #   uri: https://github.com/hhzero/gitsite/discussions
      external: true
  git:
    base-url: https://github.com/hhzero/gitsite/blob/main/source
  contact:
    name: zhangzr
    github: https://github.com/hhzero/gitsite
    twitter: https://twitter.com/zhzero
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: true
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: disqus
      name: gitsite
    analytics:
      provider: google
      gtag: 

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
